### ISSUE TITLE
Tags between 8.1.9 and 8.1.0 are pointing to the wrong commit

### ISSUE THREAD

**Issue by dan2k3k4** [drupal/core#1]
See: https://github.com/drupal/core/releases?after=8.2.0 - everything below 8.1.9 to 8.1.0 points to: https://github.com/drupal/core/commit/9bd8aa7ab6871b553c114f88fdec5223652b3740

Where as drupal-composer project is correct:
https://github.com/drupal-composer/drupal-core/releases/tag/8.1.1

**Comment by Leksat** [comment]
Some more info.

We noticed this during a fail of a production deployment.

A temporary fix we used:

> Adding the following entry to the `repositories` section fixed that for me:
> 
>         {
>             "type": "vcs",
>             "url": "https://github.com/drupal-composer/drupal-core"
>         },

**Comment by ryanaslett** [comment]
Indeed. There was a bug in the original subtree splits, and when I re-ran it, I didnt re-run 8.1.x as it is already outdated/unsupported. I'll do that now.

**Comment by ryanaslett** [comment]
Okay, the rest of the subtree splits are running, but drupal/core is now up to date for both 8.1.x and 8.0.x
